# synonyms.py

# Define synonyms for more flexible matching
SYNONYMS = {
    'study': ['study', 'learning', 'revision', 'education', 'reading', 'research', 'analysis'],
    'best time': ['best time', 'ideal time', 'perfect time', 'optimal time', 'great time'],
    'tips': ['tips', 'advice', 'suggestions', 'hints', 'recommendations', 'guidelines', 'strategies'],
    'test': ['test', 'exam', 'assessment', 'evaluation', 'quiz'],
    'homework': ['homework', 'assignments', 'tasks', 'projects'],
    'concentration': ['concentration', 'focus', 'attention', 'mindfulness', 'awareness'],
    'motivation': ['motivation', 'drive', 'inspiration', 'ambition', 'determination'],
    'productivity': ['productivity', 'efficiency', 'output', 'performance'],
    'goal': ['goal', 'objective', 'aim', 'target', 'purpose'],
    'schedule': ['schedule', 'timetable', 'plan', 'calendar', 'agenda'],
    'revision': ['revision', 'review', 'recap', 'refresh', 'reexamine'],
    'note-taking': ['note-taking', 'notetaking', 'jotting down', 'scribbling'],
    'memory': ['memory', 'recall', 'remembrance', 'recollection', 'recognition'],
    'strategy': ['strategy', 'approach', 'plan', 'method', 'technique'],
    'study environment': ['study environment', 'study space', 'learning area', 'workspace'],
    'resources': ['resources', 'materials', 'tools', 'supplies', 'aids'],
    'understanding': ['understanding', 'comprehension', 'grasp', 'insight', 'awareness'],
    'engagement': ['engagement', 'participation', 'involvement', 'commitment'],
    'analysis': ['analysis', 'examination', 'scrutiny', 'inspection', 'review'],
    'feedback': ['feedback', 'critique', 'input', 'comments', 'response'],
    'collaboration': ['collaboration', 'teamwork', 'cooperation', 'partnership'],
    'goal setting': ['goal setting', 'aim setting', 'objective setting'],
    'break': ['break', 'pause', 'rest', 'intermission', 'recess'],
    'success': ['success', 'achievement', 'accomplishment', 'victory'],
    'study group': ['study group', 'study team', 'learning group'],
    'technology': ['technology', 'tools', 'software', 'apps', 'gadgets'],
    'health': ['health', 'wellness', 'fitness', 'well-being'],
    'routine': ['routine', 'schedule', 'regimen', 'pattern', 'habit'],
    'improvement': ['improvement', 'enhancement', 'advancement', 'progress', 'growth'],
    'goal achievement': ['goal achievement', 'objective fulfillment', 'goal realization'],
    'learning style': ['learning style', 'learning method', 'educational approach'],
    'anxiety': ['anxiety', 'stress', 'nervousness', 'worry', 'apprehension'],
    'reading comprehension': ['reading comprehension', 'text understanding', 'literacy'],
    'critical thinking': ['critical thinking', 'analysis', 'evaluation', 'reasoning'],
    'time management': ['time management', 'scheduling', 'planning', 'organizing'],
    'application': ['application', 'use', 'implementation', 'execution'],
    'questioning': ['questioning', 'inquiry', 'interrogation', 'querying'],
    'curiosity': ['curiosity', 'inquisitiveness', 'wonder', 'interest'],
    'self-assessment': ['self-assessment', 'self-evaluation', 'self-review'],
    'communication': ['communication', 'interaction', 'dialogue', 'conversation'],
    'study habits': ['study habits', 'learning practices', 'academic routines'],
    'problem-solving': ['problem-solving', 'troubleshooting', 'resolution', 'finding solutions'],
    'creativity': ['creativity', 'imagination', 'innovation', 'originality'],
    'emotional intelligence': ['emotional intelligence', 'EQ', 'social skills'],
    'resilience': ['resilience', 'perseverance', 'tenacity', 'grit'],
    'active learning': ['active learning', 'participatory learning', 'engaged learning'],
    'motivation techniques': ['motivation techniques', 'inspiration methods', 'encouragement strategies'],
    'study aids': ['study aids', 'learning tools', 'educational resources'],
    'practice': ['practice', 'exercise', 'rehearsal', 'application'],
    'self-discipline': ['self-discipline', 'willpower', 'self-control', 'self-regulation'],
    'listening skills': ['listening skills', 'hearing abilities', 'auditory skills'],
    'visual learning': ['visual learning', 'graphic learning', 'picture learning'],
    'tactile learning': ['tactile learning', 'hands-on learning', 'kinesthetic learning'],
    'online resources': ['online resources', 'web tools', 'digital materials'],
    'educational podcasts': ['educational podcasts', 'learning audio', 'informative broadcasts'],
    'interactive learning': ['interactive learning', 'engaged learning', 'participatory education'],
    'study techniques': ['study techniques', 'learning strategies', 'academic methods'],
    'goal review': ['goal review', 'objective assessment', 'target evaluation'],
    'personal growth': ['personal growth', 'self-improvement', 'development'],
    'mind mapping': ['mind mapping', 'visual thinking', 'concept mapping'],
    'mental exercises': ['mental exercises', 'brain workouts', 'cognitive training'],
    'work-life balance': ['work-life balance', 'personal balance', 'life equilibrium'],
    'academic integrity': ['academic integrity', 'ethical standards', 'honesty in education'],
    'learning outcomes': ['learning outcomes', 'educational results', 'academic performance'],
    'focus techniques': ['focus techniques', 'concentration methods', 'attention strategies'],
    'self-reflection': ['self-reflection', 'introspection', 'self-examination'],
    'testing strategies': ['testing strategies', 'exam techniques', 'assessment methods'],
    'discussion': ['discussion', 'debate', 'dialogue', 'conversation'],
    'persistence': ['persistence', 'perseverance', 'determination', 'tenacity'],
    'study resources': ['study resources', 'learning materials', 'academic aids'],
    'mental wellness': ['mental wellness', 'psychological health', 'emotional well-being'],
    'time allocation': ['time allocation', 'time distribution', 'time division'],
    'academic performance': ['academic performance', 'scholastic achievement', 'educational success'],
    'performance review': ['performance review', 'evaluation', 'assessment'],
    'self-care': ['self-care', 'personal well-being', 'health maintenance'],
    'effective communication': ['effective communication', 'clear dialogue', 'articulate interaction'],
    'procrastination': ['procrastination', 'delaying', 'putting off', 'stalling'],
    'study methods': ['study methods', 'learning techniques', 'educational strategies'],
    'distractions': ['distractions', 'interruptions', 'diversions', 'obstacles'],
    'academic support': ['academic support', 'learning assistance', 'educational help'],
    'goal tracking': ['goal tracking', 'objective monitoring', 'target assessment'],
    'creativity techniques': ['creativity techniques', 'innovation methods', 'imaginative strategies'],
    'problem analysis': ['problem analysis', 'issue examination', 'challenge evaluation'],
    'academic resources': ['academic resources', 'educational tools', 'learning materials'],
    'study lifestyle': ['study lifestyle', 'academic way of life', 'learning habits'],
    'critical review': ['critical review', 'evaluation', 'assessment', 'analysis'],
    'self-directed learning': ['self-directed learning', 'autonomous learning', 'independent study'],
    'social interaction': ['social interaction', 'peer engagement', 'community involvement'],
    'academic goals': ['academic goals', 'educational aims', 'learning objectives'],
    'positive mindset': ['positive mindset', 'optimistic outlook', 'constructive attitude'],
    'confidence': ['confidence', 'self-assurance', 'belief', 'faith'],
    'study break': ['study break', 'pause', 'intermission', 'respite'],
    'reading strategies': ['reading strategies', 'literacy methods', 'comprehension techniques'],
    'educational technology': ['educational technology', 'learning tools', 'teaching resources'],
    'mindfulness practices': ['mindfulness practices', 'awareness techniques', 'focus strategies'],
    'resource management': ['resource management', 'tool allocation', 'material organization'],
    'learning objectives': ['learning objectives', 'educational goals', 'academic aims'],
    'academic planning': ['academic planning', 'education strategy', 'learning roadmap'],
    'effective study': ['effective study', 'successful learning', 'efficient education'],
    'self-improvement': ['self-improvement', 'personal development', 'self-growth'],
    'academic advising': ['academic advising', 'educational guidance', 'student support'],
    'time utilization': ['time utilization', 'time use', 'time efficiency'],
    'study progress': ['study progress', 'learning advancement', 'academic growth'],
    'educational evaluation': ['educational evaluation', 'academic assessment', 'learning review'],
    'communication skills': ['communication skills', 'interpersonal skills', 'conversational abilities'],
    'self-organization': ['self-organization', 'personal organization', 'task management'],
    'academic challenges': ['academic challenges', 'educational difficulties', 'learning obstacles'],
    'interpersonal skills': ['interpersonal skills', 'people skills', 'social abilities'],
    'networking': ['networking', 'connecting', 'relationship building'],
    'work ethic': ['work ethic', 'professionalism', 'dedication'],
    'cognitive skills': ['cognitive skills', 'mental abilities', 'thinking skills'],
    'goal setting techniques': ['goal setting techniques', 'objective formulation methods', 'target planning strategies'],
    'content mastery': ['content mastery', 'subject knowledge', 'topic expertise'],
    'academic success': ['academic success', 'educational achievement', 'scholarly accomplishment'],
    'study skills': ['study skills', 'learning abilities', 'educational competencies'],
    'study challenges': ['study challenges', 'learning difficulties', 'academic hurdles'],
    'collaborative learning': ['collaborative learning', 'group study', 'team-based education'],
    'learning feedback': ['learning feedback', 'educational input', 'study critique'],
    'academic honesty': ['academic honesty', 'integrity in education', 'ethical conduct'],
    'social learning': ['social learning', 'peer education', 'collaborative knowledge'],
    'professional development': ['professional development', 'career growth', 'skill enhancement'],
    'emotional support': ['emotional support', 'psychological aid', 'mental assistance'],
    'creative problem-solving': ['creative problem-solving', 'innovative solutions', 'original thinking'],
    'academic collaboration': ['academic collaboration', 'educational teamwork', 'joint learning efforts'],
    'learning challenges': ['learning challenges', 'educational obstacles', 'academic difficulties'],
    'motivation methods': ['motivation methods', 'incentive strategies', 'encouragement techniques'],
    'task management': ['task management', 'assignment organization', 'work prioritization'],
    'self-advocacy': ['self-advocacy', 'personal representation', 'self-promotion'],
    'personal accountability': ['personal accountability', 'self-responsibility', 'individual ownership'],
    'learning facilitation': ['learning facilitation', 'education support', 'teaching assistance'],
    'knowledge retention': ['knowledge retention', 'memory maintenance', 'information preservation'],
    'educational achievement': ['educational achievement', 'academic success', 'scholastic accomplishment'],
    'learning efficiency': ['learning efficiency', 'educational productivity', 'study effectiveness'],
    'study frameworks': ['study frameworks', 'learning structures', 'academic models'],
    'evaluation methods': ['evaluation methods', 'assessment techniques', 'testing strategies'],
    'study insights': ['study insights', 'learning observations', 'educational reflections'],
    'academic growth': ['academic growth', 'educational advancement', 'scholarly development'],
    'study mastery': ['study mastery', 'learning expertise', 'subject proficiency'],
    'career planning': ['career planning', 'professional development', 'job strategy'],
    'self-motivation': ['self-motivation', 'intrinsic drive', 'personal initiative'],
    'goal achievement strategies': ['goal achievement strategies', 'objective realization methods', 'target success tactics'],
    'academic support services': ['academic support services', 'learning assistance programs', 'educational resources'],
    'study techniques': ['study techniques', 'learning methods', 'educational practices'],
    'educational workshops': ['educational workshops', 'learning seminars', 'knowledge sessions'],
    'educational resources': ['educational resources', 'learning materials', 'academic aids'],
    'study': ['study', 'learning', 'revision', 'education', 'reading', 'research', 'analysis', 'academic work', 'homework', 'preparation'],
    'mental health': ['mental health', 'emotional well-being', 'psychological health', 'emotional health', 'wellness', 'mind health', 'mental wellness', 'cognitive health'],
    'stress': ['stress', 'tension', 'pressure', 'anxiety', 'worry', 'nervousness', 'unease', 'strain', 'frustration', 'stress management'],
    'mindfulness': ['mindfulness', 'awareness', 'present moment', 'meditation', 'focus', 'consciousness', 'attention', 'mindful breathing'],
    'motivation': ['motivation', 'inspiration', 'drive', 'determination', 'ambition', 'enthusiasm', 'passion', 'encouragement'],
    'self-care': ['self-care', 'well-being', 'self-help', 'self-nurturing', 'personal care', 'health maintenance'],
    'relaxation': ['relaxation', 'calmness', 'tranquility', 'peace', 'rest', 'unwinding', 'decompression'],
    'coping': ['coping', 'dealing', 'managing', 'handling', 'navigating', 'overcoming'],
    'support': ['support', 'assistance', 'help', 'guidance', 'aid', 'backing', 'encouragement'],
    'emotional intelligence': ['emotional intelligence', 'EQ', 'empathy', 'self-awareness', 'social skills', 'emotional awareness'],
    'goal setting': ['goal setting', 'planning', 'objectives', 'target setting', 'aiming', 'aspiration'],
    'time management': ['time management', 'time organization', 'schedule management', 'prioritization', 'planning'],
    'study breaks': ['study breaks', 'rest periods', 'pauses', 'intermissions', 'time off'],
    'personal development': ['personal development', 'self-improvement', 'growth', 'advancement', 'enrichment'],
    'resilience': ['resilience', 'mental toughness', 'adaptability', 'bounce back', 'fortitude'],
    'mindset': ['mindset', 'attitude', 'perspective', 'outlook', 'mental framework'],
    'productivity': ['productivity', 'efficiency', 'effectiveness', 'output', 'performance'],
    'healthy habits': ['healthy habits', 'wellness practices', 'good habits', 'lifestyle choices', 'routine'],
    'peer support': ['peer support', 'friendship', 'companionship', 'fellowship', 'community'],
    'academic pressure': ['academic pressure', 'school pressure', 'scholarly stress', 'educational demands'],
    'feedback': ['feedback', 'response', 'evaluation', 'critique', 'input', 'assessment'],
    'counseling': ['counseling', 'therapy', 'guidance', 'advice', 'supportive dialogue'],
    'self-reflection': ['self-reflection', 'introspection', 'self-assessment', 'personal insight', 'self-evaluation'],
    'cognitive behavioral techniques': ['cognitive behavioral techniques', 'CBT', 'cognitive restructuring', 'behavioral strategies'],
    'stress-relief': ['stress-relief', 'stress reduction', 'relaxation techniques', 'calming strategies'],
    'sleep hygiene': ['sleep hygiene', 'sleep practices', 'rest habits', 'sleep quality'],
    'nutrition': ['nutrition', 'diet', 'eating habits', 'food choices', 'nutritional health'],
    'study skills': ['study skills', 'learning techniques', 'academic skills', 'study methods', 'learning strategies'],
    'online resources': ['online resources', 'web-based tools', 'digital materials', 'internet resources'],
    'burnout': ['burnout', 'exhaustion', 'fatigue', 'overwhelm', 'mental drain'],
    'self-esteem': ['self-esteem', 'self-worth', 'confidence', 'self-image', 'self-regard'],
    'motivation techniques': ['motivation techniques', 'motivational strategies', 'inspiration methods'],
    'goal achievement': ['goal achievement', 'reaching goals', 'success realization'],
    'emotional support': ['emotional support', 'affection', 'care', 'concern', 'compassion'],
    'stress relief exercises': ['stress relief exercises', 'stress management activities', 'calming practices'],
    'study techniques': ['study techniques', 'learning approaches', 'study methods', 'academic strategies'],
    'mental exercises': ['mental exercises', 'brain training', 'cognitive activities'],
    'social connection': ['social connection', 'relationships', 'community engagement'],
    'motivation boosters': ['motivation boosters', 'inspiration triggers', 'encouragement tactics'],
    'distraction management': ['distraction management', 'focus techniques', 'concentration strategies'],
    'healthy relationships': ['healthy relationships', 'positive connections', 'supportive friendships'],
    'creativity': ['creativity', 'innovation', 'imagination', 'originality'],
    'self-discipline': ['self-discipline', 'willpower', 'self-control', 'personal governance'],
    'mental clarity': ['mental clarity', 'clear thinking', 'cognitive sharpness'],
    'life balance': ['life balance', 'work-life balance', 'equilibrium', 'harmony'],
    'academic success': ['academic success', 'scholarly achievement', 'educational accomplishments'],
    'study environment': ['study environment', 'study space', 'learning area'],
    'time allocation': ['time allocation', 'time distribution', 'schedule management'],
    'study motivation': ['study motivation', 'academic drive', 'learning inspiration'],
    'self-awareness': ['self-awareness', 'personal insight', 'introspection'],
    'wellness checks': ['wellness checks', 'health assessments', 'wellness evaluations'],
    'affirmations': ['affirmations', 'positive statements', 'self-affirmations', 'encouragements'],
    'supportive dialogue': ['supportive dialogue', 'open conversations', 'friendly discussions'],
    'breathing techniques': ['breathing techniques', 'breathing exercises', 'relaxation breathing'],
    'peer mentoring': ['peer mentoring', 'student mentoring', 'academic guidance'],
    'growth mindset': ['growth mindset', 'adaptive thinking', 'developmental perspective'],
    'study methods': ['study methods', 'learning styles', 'academic approaches'],
    'resourcefulness': ['resourcefulness', 'problem-solving', 'adaptability'],
    'feedback mechanism': ['feedback mechanism', 'evaluation system', 'response process'],
    'achievement tracking': ['achievement tracking', 'goal monitoring', 'progress assessment'],
    'academic integrity': ['academic integrity', 'honesty in scholarship', 'ethical standards'],
    'creative outlets': ['creative outlets', 'expressive activities', 'artistic pursuits'],
    'wellness initiatives': ['wellness initiatives', 'health programs', 'wellness projects'],
    'proactive behavior': ['proactive behavior', 'initiative', 'anticipatory actions'],
    'mindfulness practice': ['mindfulness practice', 'meditative exercises', 'awareness activities'],
    'resilience training': ['resilience training', 'mental toughness building', 'fortitude exercises'],
    'community engagement': ['community engagement', 'social involvement', 'public participation'],
    'study habits': ['study habits', 'academic routines', 'learning practices'],
    'emotional regulation': ['emotional regulation', 'emotion management', 'affective control'],
    'positive thinking': ['positive thinking', 'optimism', 'constructive mindset'],
    'problem-solving': ['problem-solving', 'critical thinking', 'analytical skills'],
    'creative thinking': ['creative thinking', 'innovative thought', 'imaginative reasoning'],
    'academic resources': ['academic resources', 'educational tools', 'scholarly materials'],
    'inspiration': ['inspiration', 'stimulus', 'encouragement', 'upliftment'],
    'self-care practices': ['self-care practices', 'wellness routines', 'self-nurturing activities'],
    'study techniques': ['study techniques', 'learning strategies', 'academic approaches'],
    'focus techniques': ['focus techniques', 'concentration strategies', 'attention management'],
    'time optimization': ['time optimization', 'schedule efficiency', 'time effectiveness'],
    'study accountability': ['study accountability', 'responsibility', 'commitment'],
    'academic challenges': ['academic challenges', 'scholarly obstacles', 'educational difficulties'],
    'virtual support': ['virtual support', 'online assistance', 'digital help'],
    'life skills': ['life skills', 'practical skills', 'personal development skills'],
    'academic performance': ['academic performance', 'scholarly results', 'educational achievements'],
    'balance and harmony': ['balance and harmony', 'equilibrium', 'well-roundedness'],
    'emotional expression': ['emotional expression', 'feelings sharing', 'affective communication'],
    'learning from mistakes': ['learning from mistakes', 'error analysis', 'experience-based learning'],
    'networking': ['networking', 'relationship building', 'connecting with peers'],
    'healthy coping mechanisms': ['healthy coping mechanisms', 'adaptive strategies', 'constructive responses'],
    'study readiness': ['study readiness', 'academic preparedness', 'learning readiness'],

}
